/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadTokenRouteImport } from './routes/lead.$token'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as PublicSlugIndexRouteImport } from './routes/public.$slug.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as PublicSlugTableIdRouteImport } from './routes/public.$slug.$tableId'
import { Route as ApiPublicTablesRouteImport } from './routes/api/public/tables'
import { Route as ApiPublicSystemFieldsRouteImport } from './routes/api/public/system-fields'
import { Route as ApiPublicRecordsRouteImport } from './routes/api/public/records'
import { Route as ApiPublicPlatformLabelsRouteImport } from './routes/api/public/platform-labels'
import { Route as ApiPublicOrganizationsRouteImport } from './routes/api/public/organizations'
import { Route as ApiPublicOrganizationCategoriesRouteImport } from './routes/api/public/organization-categories'
import { Route as ApiPublicInstanceSettingsRouteImport } from './routes/api/public/instance-settings'
import { Route as AuthenticatedMeApplicationsRouteImport } from './routes/_authenticated.me.applications'
import { Route as PublicSlugTableIdIndexRouteImport } from './routes/public.$slug.$tableId.index'
import { Route as AuthenticatedAppOrgSlugIndexRouteImport } from './routes/_authenticated.app.$orgSlug.index'
import { Route as PublicSlugCampaignsRecordIdRouteImport } from './routes/public.$slug.campaigns.$recordId'
import { Route as PublicSlugTableIdFormRouteImport } from './routes/public.$slug.$tableId.form'
import { Route as PublicSlugTableIdRecordIdRouteImport } from './routes/public.$slug.$tableId.$recordId'
import { Route as ApiPublicViacepCepRouteImport } from './routes/api/public/viacep.$cep'
import { Route as ApiPublicLeadTokenRouteImport } from './routes/api/public/lead/$token'
import { Route as ApiPublicFormSchemaViewIdRouteImport } from './routes/api/public/form-schema/$viewId'
import { Route as ApiPublicCategorySchemaCategoryIdRouteImport } from './routes/api/public/category-schema.$categoryId'
import { Route as ApiPublicCategoryLayoutCategoryIdRouteImport } from './routes/api/public/category-layout.$categoryId'
import { Route as ApiPublicCampaignsRecordIdRouteImport } from './routes/api/public/campaigns/$recordId'
import { Route as ApiPublicSlugTableIdRouteImport } from './routes/api/public/$slug/$tableId'
import { Route as AuthenticatedAppOrgSlugMembersRouteImport } from './routes/_authenticated.app.$orgSlug.members'
import { Route as AuthenticatedAppOrgSlugConversationsRouteImport } from './routes/_authenticated.app.$orgSlug.conversations'
import { Route as AuthenticatedAppOrgSlugCalendarRouteImport } from './routes/_authenticated.app.$orgSlug.calendar'
import { Route as ApiPublicSlugTableIdSubmitRouteImport } from './routes/api/public/$slug/$tableId.submit'
import { Route as ApiPublicSlugTableIdRecordIdRouteImport } from './routes/api/public/$slug/$tableId.$recordId'
import { Route as AuthenticatedAppOrgSlugConversationsConversationIdRouteImport } from './routes/_authenticated.app.$orgSlug.conversations.$conversationId'
import { Route as AuthenticatedAppOrgSlugTablesTableIdIndexRouteImport } from './routes/_authenticated.app.$orgSlug.tables.$tableId.index'
import { Route as AuthenticatedAppOrgSlugTablesTableIdSchemaRouteImport } from './routes/_authenticated.app.$orgSlug.tables.$tableId.schema'

const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadTokenRoute = LeadTokenRouteImport.update({
  id: '/lead/$token',
  path: '/lead/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicSlugIndexRoute = PublicSlugIndexRouteImport.update({
  id: '/public/$slug/',
  path: '/public/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicSlugTableIdRoute = PublicSlugTableIdRouteImport.update({
  id: '/public/$slug/$tableId',
  path: '/public/$slug/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTablesRoute = ApiPublicTablesRouteImport.update({
  id: '/api/public/tables',
  path: '/api/public/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSystemFieldsRoute = ApiPublicSystemFieldsRouteImport.update({
  id: '/api/public/system-fields',
  path: '/api/public/system-fields',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecordsRoute = ApiPublicRecordsRouteImport.update({
  id: '/api/public/records',
  path: '/api/public/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlatformLabelsRoute = ApiPublicPlatformLabelsRouteImport.update({
  id: '/api/public/platform-labels',
  path: '/api/public/platform-labels',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrganizationsRoute = ApiPublicOrganizationsRouteImport.update({
  id: '/api/public/organizations',
  path: '/api/public/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrganizationCategoriesRoute =
  ApiPublicOrganizationCategoriesRouteImport.update({
    id: '/api/public/organization-categories',
    path: '/api/public/organization-categories',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicInstanceSettingsRoute =
  ApiPublicInstanceSettingsRouteImport.update({
    id: '/api/public/instance-settings',
    path: '/api/public/instance-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMeApplicationsRoute =
  AuthenticatedMeApplicationsRouteImport.update({
    id: '/me/applications',
    path: '/me/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicSlugTableIdIndexRoute = PublicSlugTableIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicSlugTableIdRoute,
} as any)
const AuthenticatedAppOrgSlugIndexRoute =
  AuthenticatedAppOrgSlugIndexRouteImport.update({
    id: '/app/$orgSlug/',
    path: '/app/$orgSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicSlugCampaignsRecordIdRoute =
  PublicSlugCampaignsRecordIdRouteImport.update({
    id: '/public/$slug/campaigns/$recordId',
    path: '/public/$slug/campaigns/$recordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PublicSlugTableIdFormRoute = PublicSlugTableIdFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => PublicSlugTableIdRoute,
} as any)
const PublicSlugTableIdRecordIdRoute =
  PublicSlugTableIdRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => PublicSlugTableIdRoute,
  } as any)
const ApiPublicViacepCepRoute = ApiPublicViacepCepRouteImport.update({
  id: '/api/public/viacep/$cep',
  path: '/api/public/viacep/$cep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadTokenRoute = ApiPublicLeadTokenRouteImport.update({
  id: '/api/public/lead/$token',
  path: '/api/public/lead/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFormSchemaViewIdRoute =
  ApiPublicFormSchemaViewIdRouteImport.update({
    id: '/api/public/form-schema/$viewId',
    path: '/api/public/form-schema/$viewId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCategorySchemaCategoryIdRoute =
  ApiPublicCategorySchemaCategoryIdRouteImport.update({
    id: '/api/public/category-schema/$categoryId',
    path: '/api/public/category-schema/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCategoryLayoutCategoryIdRoute =
  ApiPublicCategoryLayoutCategoryIdRouteImport.update({
    id: '/api/public/category-layout/$categoryId',
    path: '/api/public/category-layout/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCampaignsRecordIdRoute =
  ApiPublicCampaignsRecordIdRouteImport.update({
    id: '/api/public/campaigns/$recordId',
    path: '/api/public/campaigns/$recordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSlugTableIdRoute = ApiPublicSlugTableIdRouteImport.update({
  id: '/api/public/$slug/$tableId',
  path: '/api/public/$slug/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppOrgSlugMembersRoute =
  AuthenticatedAppOrgSlugMembersRouteImport.update({
    id: '/app/$orgSlug/members',
    path: '/app/$orgSlug/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppOrgSlugConversationsRoute =
  AuthenticatedAppOrgSlugConversationsRouteImport.update({
    id: '/app/$orgSlug/conversations',
    path: '/app/$orgSlug/conversations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppOrgSlugCalendarRoute =
  AuthenticatedAppOrgSlugCalendarRouteImport.update({
    id: '/app/$orgSlug/calendar',
    path: '/app/$orgSlug/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicSlugTableIdSubmitRoute =
  ApiPublicSlugTableIdSubmitRouteImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => ApiPublicSlugTableIdRoute,
  } as any)
const ApiPublicSlugTableIdRecordIdRoute =
  ApiPublicSlugTableIdRecordIdRouteImport.update({
    id: '/$recordId',
    path: '/$recordId',
    getParentRoute: () => ApiPublicSlugTableIdRoute,
  } as any)
const AuthenticatedAppOrgSlugConversationsConversationIdRoute =
  AuthenticatedAppOrgSlugConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedAppOrgSlugConversationsRoute,
  } as any)
const AuthenticatedAppOrgSlugTablesTableIdIndexRoute =
  AuthenticatedAppOrgSlugTablesTableIdIndexRouteImport.update({
    id: '/app/$orgSlug/tables/$tableId/',
    path: '/app/$orgSlug/tables/$tableId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppOrgSlugTablesTableIdSchemaRoute =
  AuthenticatedAppOrgSlugTablesTableIdSchemaRouteImport.update({
    id: '/app/$orgSlug/tables/$tableId/schema',
    path: '/app/$orgSlug/tables/$tableId/schema',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lead/$token': typeof LeadTokenRoute
  '/me/applications': typeof AuthenticatedMeApplicationsRoute
  '/api/public/instance-settings': typeof ApiPublicInstanceSettingsRoute
  '/api/public/organization-categories': typeof ApiPublicOrganizationCategoriesRoute
  '/api/public/organizations': typeof ApiPublicOrganizationsRoute
  '/api/public/platform-labels': typeof ApiPublicPlatformLabelsRoute
  '/api/public/records': typeof ApiPublicRecordsRoute
  '/api/public/system-fields': typeof ApiPublicSystemFieldsRoute
  '/api/public/tables': typeof ApiPublicTablesRoute
  '/public/$slug/$tableId': typeof PublicSlugTableIdRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/public/$slug/': typeof PublicSlugIndexRoute
  '/app/$orgSlug/calendar': typeof AuthenticatedAppOrgSlugCalendarRoute
  '/app/$orgSlug/conversations': typeof AuthenticatedAppOrgSlugConversationsRouteWithChildren
  '/app/$orgSlug/members': typeof AuthenticatedAppOrgSlugMembersRoute
  '/api/public/$slug/$tableId': typeof ApiPublicSlugTableIdRouteWithChildren
  '/api/public/campaigns/$recordId': typeof ApiPublicCampaignsRecordIdRoute
  '/api/public/category-layout/$categoryId': typeof ApiPublicCategoryLayoutCategoryIdRoute
  '/api/public/category-schema/$categoryId': typeof ApiPublicCategorySchemaCategoryIdRoute
  '/api/public/form-schema/$viewId': typeof ApiPublicFormSchemaViewIdRoute
  '/api/public/lead/$token': typeof ApiPublicLeadTokenRoute
  '/api/public/viacep/$cep': typeof ApiPublicViacepCepRoute
  '/public/$slug/$tableId/$recordId': typeof PublicSlugTableIdRecordIdRoute
  '/public/$slug/$tableId/form': typeof PublicSlugTableIdFormRoute
  '/public/$slug/campaigns/$recordId': typeof PublicSlugCampaignsRecordIdRoute
  '/app/$orgSlug/': typeof AuthenticatedAppOrgSlugIndexRoute
  '/public/$slug/$tableId/': typeof PublicSlugTableIdIndexRoute
  '/app/$orgSlug/conversations/$conversationId': typeof AuthenticatedAppOrgSlugConversationsConversationIdRoute
  '/api/public/$slug/$tableId/$recordId': typeof ApiPublicSlugTableIdRecordIdRoute
  '/api/public/$slug/$tableId/submit': typeof ApiPublicSlugTableIdSubmitRoute
  '/app/$orgSlug/tables/$tableId/schema': typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  '/app/$orgSlug/tables/$tableId/': typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/lead/$token': typeof LeadTokenRoute
  '/me/applications': typeof AuthenticatedMeApplicationsRoute
  '/api/public/instance-settings': typeof ApiPublicInstanceSettingsRoute
  '/api/public/organization-categories': typeof ApiPublicOrganizationCategoriesRoute
  '/api/public/organizations': typeof ApiPublicOrganizationsRoute
  '/api/public/platform-labels': typeof ApiPublicPlatformLabelsRoute
  '/api/public/records': typeof ApiPublicRecordsRoute
  '/api/public/system-fields': typeof ApiPublicSystemFieldsRoute
  '/api/public/tables': typeof ApiPublicTablesRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/public/$slug': typeof PublicSlugIndexRoute
  '/app/$orgSlug/calendar': typeof AuthenticatedAppOrgSlugCalendarRoute
  '/app/$orgSlug/conversations': typeof AuthenticatedAppOrgSlugConversationsRouteWithChildren
  '/app/$orgSlug/members': typeof AuthenticatedAppOrgSlugMembersRoute
  '/api/public/$slug/$tableId': typeof ApiPublicSlugTableIdRouteWithChildren
  '/api/public/campaigns/$recordId': typeof ApiPublicCampaignsRecordIdRoute
  '/api/public/category-layout/$categoryId': typeof ApiPublicCategoryLayoutCategoryIdRoute
  '/api/public/category-schema/$categoryId': typeof ApiPublicCategorySchemaCategoryIdRoute
  '/api/public/form-schema/$viewId': typeof ApiPublicFormSchemaViewIdRoute
  '/api/public/lead/$token': typeof ApiPublicLeadTokenRoute
  '/api/public/viacep/$cep': typeof ApiPublicViacepCepRoute
  '/public/$slug/$tableId/$recordId': typeof PublicSlugTableIdRecordIdRoute
  '/public/$slug/$tableId/form': typeof PublicSlugTableIdFormRoute
  '/public/$slug/campaigns/$recordId': typeof PublicSlugCampaignsRecordIdRoute
  '/app/$orgSlug': typeof AuthenticatedAppOrgSlugIndexRoute
  '/public/$slug/$tableId': typeof PublicSlugTableIdIndexRoute
  '/app/$orgSlug/conversations/$conversationId': typeof AuthenticatedAppOrgSlugConversationsConversationIdRoute
  '/api/public/$slug/$tableId/$recordId': typeof ApiPublicSlugTableIdRecordIdRoute
  '/api/public/$slug/$tableId/submit': typeof ApiPublicSlugTableIdSubmitRoute
  '/app/$orgSlug/tables/$tableId/schema': typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  '/app/$orgSlug/tables/$tableId': typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/lead/$token': typeof LeadTokenRoute
  '/_authenticated/me/applications': typeof AuthenticatedMeApplicationsRoute
  '/api/public/instance-settings': typeof ApiPublicInstanceSettingsRoute
  '/api/public/organization-categories': typeof ApiPublicOrganizationCategoriesRoute
  '/api/public/organizations': typeof ApiPublicOrganizationsRoute
  '/api/public/platform-labels': typeof ApiPublicPlatformLabelsRoute
  '/api/public/records': typeof ApiPublicRecordsRoute
  '/api/public/system-fields': typeof ApiPublicSystemFieldsRoute
  '/api/public/tables': typeof ApiPublicTablesRoute
  '/public/$slug/$tableId': typeof PublicSlugTableIdRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/public/$slug/': typeof PublicSlugIndexRoute
  '/_authenticated/app/$orgSlug/calendar': typeof AuthenticatedAppOrgSlugCalendarRoute
  '/_authenticated/app/$orgSlug/conversations': typeof AuthenticatedAppOrgSlugConversationsRouteWithChildren
  '/_authenticated/app/$orgSlug/members': typeof AuthenticatedAppOrgSlugMembersRoute
  '/api/public/$slug/$tableId': typeof ApiPublicSlugTableIdRouteWithChildren
  '/api/public/campaigns/$recordId': typeof ApiPublicCampaignsRecordIdRoute
  '/api/public/category-layout/$categoryId': typeof ApiPublicCategoryLayoutCategoryIdRoute
  '/api/public/category-schema/$categoryId': typeof ApiPublicCategorySchemaCategoryIdRoute
  '/api/public/form-schema/$viewId': typeof ApiPublicFormSchemaViewIdRoute
  '/api/public/lead/$token': typeof ApiPublicLeadTokenRoute
  '/api/public/viacep/$cep': typeof ApiPublicViacepCepRoute
  '/public/$slug/$tableId/$recordId': typeof PublicSlugTableIdRecordIdRoute
  '/public/$slug/$tableId/form': typeof PublicSlugTableIdFormRoute
  '/public/$slug/campaigns/$recordId': typeof PublicSlugCampaignsRecordIdRoute
  '/_authenticated/app/$orgSlug/': typeof AuthenticatedAppOrgSlugIndexRoute
  '/public/$slug/$tableId/': typeof PublicSlugTableIdIndexRoute
  '/_authenticated/app/$orgSlug/conversations/$conversationId': typeof AuthenticatedAppOrgSlugConversationsConversationIdRoute
  '/api/public/$slug/$tableId/$recordId': typeof ApiPublicSlugTableIdRecordIdRoute
  '/api/public/$slug/$tableId/submit': typeof ApiPublicSlugTableIdSubmitRoute
  '/_authenticated/app/$orgSlug/tables/$tableId/schema': typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  '/_authenticated/app/$orgSlug/tables/$tableId/': typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/admin'
    | '/lead/$token'
    | '/me/applications'
    | '/api/public/instance-settings'
    | '/api/public/organization-categories'
    | '/api/public/organizations'
    | '/api/public/platform-labels'
    | '/api/public/records'
    | '/api/public/system-fields'
    | '/api/public/tables'
    | '/public/$slug/$tableId'
    | '/app/'
    | '/public/$slug/'
    | '/app/$orgSlug/calendar'
    | '/app/$orgSlug/conversations'
    | '/app/$orgSlug/members'
    | '/api/public/$slug/$tableId'
    | '/api/public/campaigns/$recordId'
    | '/api/public/category-layout/$categoryId'
    | '/api/public/category-schema/$categoryId'
    | '/api/public/form-schema/$viewId'
    | '/api/public/lead/$token'
    | '/api/public/viacep/$cep'
    | '/public/$slug/$tableId/$recordId'
    | '/public/$slug/$tableId/form'
    | '/public/$slug/campaigns/$recordId'
    | '/app/$orgSlug/'
    | '/public/$slug/$tableId/'
    | '/app/$orgSlug/conversations/$conversationId'
    | '/api/public/$slug/$tableId/$recordId'
    | '/api/public/$slug/$tableId/submit'
    | '/app/$orgSlug/tables/$tableId/schema'
    | '/app/$orgSlug/tables/$tableId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/admin'
    | '/lead/$token'
    | '/me/applications'
    | '/api/public/instance-settings'
    | '/api/public/organization-categories'
    | '/api/public/organizations'
    | '/api/public/platform-labels'
    | '/api/public/records'
    | '/api/public/system-fields'
    | '/api/public/tables'
    | '/app'
    | '/public/$slug'
    | '/app/$orgSlug/calendar'
    | '/app/$orgSlug/conversations'
    | '/app/$orgSlug/members'
    | '/api/public/$slug/$tableId'
    | '/api/public/campaigns/$recordId'
    | '/api/public/category-layout/$categoryId'
    | '/api/public/category-schema/$categoryId'
    | '/api/public/form-schema/$viewId'
    | '/api/public/lead/$token'
    | '/api/public/viacep/$cep'
    | '/public/$slug/$tableId/$recordId'
    | '/public/$slug/$tableId/form'
    | '/public/$slug/campaigns/$recordId'
    | '/app/$orgSlug'
    | '/public/$slug/$tableId'
    | '/app/$orgSlug/conversations/$conversationId'
    | '/api/public/$slug/$tableId/$recordId'
    | '/api/public/$slug/$tableId/submit'
    | '/app/$orgSlug/tables/$tableId/schema'
    | '/app/$orgSlug/tables/$tableId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explore'
    | '/_authenticated/admin'
    | '/lead/$token'
    | '/_authenticated/me/applications'
    | '/api/public/instance-settings'
    | '/api/public/organization-categories'
    | '/api/public/organizations'
    | '/api/public/platform-labels'
    | '/api/public/records'
    | '/api/public/system-fields'
    | '/api/public/tables'
    | '/public/$slug/$tableId'
    | '/_authenticated/app/'
    | '/public/$slug/'
    | '/_authenticated/app/$orgSlug/calendar'
    | '/_authenticated/app/$orgSlug/conversations'
    | '/_authenticated/app/$orgSlug/members'
    | '/api/public/$slug/$tableId'
    | '/api/public/campaigns/$recordId'
    | '/api/public/category-layout/$categoryId'
    | '/api/public/category-schema/$categoryId'
    | '/api/public/form-schema/$viewId'
    | '/api/public/lead/$token'
    | '/api/public/viacep/$cep'
    | '/public/$slug/$tableId/$recordId'
    | '/public/$slug/$tableId/form'
    | '/public/$slug/campaigns/$recordId'
    | '/_authenticated/app/$orgSlug/'
    | '/public/$slug/$tableId/'
    | '/_authenticated/app/$orgSlug/conversations/$conversationId'
    | '/api/public/$slug/$tableId/$recordId'
    | '/api/public/$slug/$tableId/submit'
    | '/_authenticated/app/$orgSlug/tables/$tableId/schema'
    | '/_authenticated/app/$orgSlug/tables/$tableId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  LeadTokenRoute: typeof LeadTokenRoute
  ApiPublicInstanceSettingsRoute: typeof ApiPublicInstanceSettingsRoute
  ApiPublicOrganizationCategoriesRoute: typeof ApiPublicOrganizationCategoriesRoute
  ApiPublicOrganizationsRoute: typeof ApiPublicOrganizationsRoute
  ApiPublicPlatformLabelsRoute: typeof ApiPublicPlatformLabelsRoute
  ApiPublicRecordsRoute: typeof ApiPublicRecordsRoute
  ApiPublicSystemFieldsRoute: typeof ApiPublicSystemFieldsRoute
  ApiPublicTablesRoute: typeof ApiPublicTablesRoute
  PublicSlugTableIdRoute: typeof PublicSlugTableIdRouteWithChildren
  PublicSlugIndexRoute: typeof PublicSlugIndexRoute
  ApiPublicSlugTableIdRoute: typeof ApiPublicSlugTableIdRouteWithChildren
  ApiPublicCampaignsRecordIdRoute: typeof ApiPublicCampaignsRecordIdRoute
  ApiPublicCategoryLayoutCategoryIdRoute: typeof ApiPublicCategoryLayoutCategoryIdRoute
  ApiPublicCategorySchemaCategoryIdRoute: typeof ApiPublicCategorySchemaCategoryIdRoute
  ApiPublicFormSchemaViewIdRoute: typeof ApiPublicFormSchemaViewIdRoute
  ApiPublicLeadTokenRoute: typeof ApiPublicLeadTokenRoute
  ApiPublicViacepCepRoute: typeof ApiPublicViacepCepRoute
  PublicSlugCampaignsRecordIdRoute: typeof PublicSlugCampaignsRecordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead/$token': {
      id: '/lead/$token'
      path: '/lead/$token'
      fullPath: '/lead/$token'
      preLoaderRoute: typeof LeadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/public/$slug/': {
      id: '/public/$slug/'
      path: '/public/$slug'
      fullPath: '/public/$slug/'
      preLoaderRoute: typeof PublicSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/public/$slug/$tableId': {
      id: '/public/$slug/$tableId'
      path: '/public/$slug/$tableId'
      fullPath: '/public/$slug/$tableId'
      preLoaderRoute: typeof PublicSlugTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tables': {
      id: '/api/public/tables'
      path: '/api/public/tables'
      fullPath: '/api/public/tables'
      preLoaderRoute: typeof ApiPublicTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/system-fields': {
      id: '/api/public/system-fields'
      path: '/api/public/system-fields'
      fullPath: '/api/public/system-fields'
      preLoaderRoute: typeof ApiPublicSystemFieldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/records': {
      id: '/api/public/records'
      path: '/api/public/records'
      fullPath: '/api/public/records'
      preLoaderRoute: typeof ApiPublicRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/platform-labels': {
      id: '/api/public/platform-labels'
      path: '/api/public/platform-labels'
      fullPath: '/api/public/platform-labels'
      preLoaderRoute: typeof ApiPublicPlatformLabelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/organizations': {
      id: '/api/public/organizations'
      path: '/api/public/organizations'
      fullPath: '/api/public/organizations'
      preLoaderRoute: typeof ApiPublicOrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/organization-categories': {
      id: '/api/public/organization-categories'
      path: '/api/public/organization-categories'
      fullPath: '/api/public/organization-categories'
      preLoaderRoute: typeof ApiPublicOrganizationCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/instance-settings': {
      id: '/api/public/instance-settings'
      path: '/api/public/instance-settings'
      fullPath: '/api/public/instance-settings'
      preLoaderRoute: typeof ApiPublicInstanceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me/applications': {
      id: '/_authenticated/me/applications'
      path: '/me/applications'
      fullPath: '/me/applications'
      preLoaderRoute: typeof AuthenticatedMeApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/public/$slug/$tableId/': {
      id: '/public/$slug/$tableId/'
      path: '/'
      fullPath: '/public/$slug/$tableId/'
      preLoaderRoute: typeof PublicSlugTableIdIndexRouteImport
      parentRoute: typeof PublicSlugTableIdRoute
    }
    '/_authenticated/app/$orgSlug/': {
      id: '/_authenticated/app/$orgSlug/'
      path: '/app/$orgSlug'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/public/$slug/campaigns/$recordId': {
      id: '/public/$slug/campaigns/$recordId'
      path: '/public/$slug/campaigns/$recordId'
      fullPath: '/public/$slug/campaigns/$recordId'
      preLoaderRoute: typeof PublicSlugCampaignsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/$slug/$tableId/form': {
      id: '/public/$slug/$tableId/form'
      path: '/form'
      fullPath: '/public/$slug/$tableId/form'
      preLoaderRoute: typeof PublicSlugTableIdFormRouteImport
      parentRoute: typeof PublicSlugTableIdRoute
    }
    '/public/$slug/$tableId/$recordId': {
      id: '/public/$slug/$tableId/$recordId'
      path: '/$recordId'
      fullPath: '/public/$slug/$tableId/$recordId'
      preLoaderRoute: typeof PublicSlugTableIdRecordIdRouteImport
      parentRoute: typeof PublicSlugTableIdRoute
    }
    '/api/public/viacep/$cep': {
      id: '/api/public/viacep/$cep'
      path: '/api/public/viacep/$cep'
      fullPath: '/api/public/viacep/$cep'
      preLoaderRoute: typeof ApiPublicViacepCepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead/$token': {
      id: '/api/public/lead/$token'
      path: '/api/public/lead/$token'
      fullPath: '/api/public/lead/$token'
      preLoaderRoute: typeof ApiPublicLeadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/form-schema/$viewId': {
      id: '/api/public/form-schema/$viewId'
      path: '/api/public/form-schema/$viewId'
      fullPath: '/api/public/form-schema/$viewId'
      preLoaderRoute: typeof ApiPublicFormSchemaViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/category-schema/$categoryId': {
      id: '/api/public/category-schema/$categoryId'
      path: '/api/public/category-schema/$categoryId'
      fullPath: '/api/public/category-schema/$categoryId'
      preLoaderRoute: typeof ApiPublicCategorySchemaCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/category-layout/$categoryId': {
      id: '/api/public/category-layout/$categoryId'
      path: '/api/public/category-layout/$categoryId'
      fullPath: '/api/public/category-layout/$categoryId'
      preLoaderRoute: typeof ApiPublicCategoryLayoutCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/campaigns/$recordId': {
      id: '/api/public/campaigns/$recordId'
      path: '/api/public/campaigns/$recordId'
      fullPath: '/api/public/campaigns/$recordId'
      preLoaderRoute: typeof ApiPublicCampaignsRecordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/$slug/$tableId': {
      id: '/api/public/$slug/$tableId'
      path: '/api/public/$slug/$tableId'
      fullPath: '/api/public/$slug/$tableId'
      preLoaderRoute: typeof ApiPublicSlugTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/$orgSlug/members': {
      id: '/_authenticated/app/$orgSlug/members'
      path: '/app/$orgSlug/members'
      fullPath: '/app/$orgSlug/members'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$orgSlug/conversations': {
      id: '/_authenticated/app/$orgSlug/conversations'
      path: '/app/$orgSlug/conversations'
      fullPath: '/app/$orgSlug/conversations'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugConversationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$orgSlug/calendar': {
      id: '/_authenticated/app/$orgSlug/calendar'
      path: '/app/$orgSlug/calendar'
      fullPath: '/app/$orgSlug/calendar'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/$slug/$tableId/submit': {
      id: '/api/public/$slug/$tableId/submit'
      path: '/submit'
      fullPath: '/api/public/$slug/$tableId/submit'
      preLoaderRoute: typeof ApiPublicSlugTableIdSubmitRouteImport
      parentRoute: typeof ApiPublicSlugTableIdRoute
    }
    '/api/public/$slug/$tableId/$recordId': {
      id: '/api/public/$slug/$tableId/$recordId'
      path: '/$recordId'
      fullPath: '/api/public/$slug/$tableId/$recordId'
      preLoaderRoute: typeof ApiPublicSlugTableIdRecordIdRouteImport
      parentRoute: typeof ApiPublicSlugTableIdRoute
    }
    '/_authenticated/app/$orgSlug/conversations/$conversationId': {
      id: '/_authenticated/app/$orgSlug/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/app/$orgSlug/conversations/$conversationId'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugConversationsConversationIdRouteImport
      parentRoute: typeof AuthenticatedAppOrgSlugConversationsRoute
    }
    '/_authenticated/app/$orgSlug/tables/$tableId/': {
      id: '/_authenticated/app/$orgSlug/tables/$tableId/'
      path: '/app/$orgSlug/tables/$tableId'
      fullPath: '/app/$orgSlug/tables/$tableId/'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugTablesTableIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$orgSlug/tables/$tableId/schema': {
      id: '/_authenticated/app/$orgSlug/tables/$tableId/schema'
      path: '/app/$orgSlug/tables/$tableId/schema'
      fullPath: '/app/$orgSlug/tables/$tableId/schema'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAppOrgSlugConversationsRouteChildren {
  AuthenticatedAppOrgSlugConversationsConversationIdRoute: typeof AuthenticatedAppOrgSlugConversationsConversationIdRoute
}

const AuthenticatedAppOrgSlugConversationsRouteChildren: AuthenticatedAppOrgSlugConversationsRouteChildren =
  {
    AuthenticatedAppOrgSlugConversationsConversationIdRoute:
      AuthenticatedAppOrgSlugConversationsConversationIdRoute,
  }

const AuthenticatedAppOrgSlugConversationsRouteWithChildren =
  AuthenticatedAppOrgSlugConversationsRoute._addFileChildren(
    AuthenticatedAppOrgSlugConversationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeApplicationsRoute: typeof AuthenticatedMeApplicationsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppOrgSlugCalendarRoute: typeof AuthenticatedAppOrgSlugCalendarRoute
  AuthenticatedAppOrgSlugConversationsRoute: typeof AuthenticatedAppOrgSlugConversationsRouteWithChildren
  AuthenticatedAppOrgSlugMembersRoute: typeof AuthenticatedAppOrgSlugMembersRoute
  AuthenticatedAppOrgSlugIndexRoute: typeof AuthenticatedAppOrgSlugIndexRoute
  AuthenticatedAppOrgSlugTablesTableIdSchemaRoute: typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  AuthenticatedAppOrgSlugTablesTableIdIndexRoute: typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeApplicationsRoute: AuthenticatedMeApplicationsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppOrgSlugCalendarRoute: AuthenticatedAppOrgSlugCalendarRoute,
  AuthenticatedAppOrgSlugConversationsRoute:
    AuthenticatedAppOrgSlugConversationsRouteWithChildren,
  AuthenticatedAppOrgSlugMembersRoute: AuthenticatedAppOrgSlugMembersRoute,
  AuthenticatedAppOrgSlugIndexRoute: AuthenticatedAppOrgSlugIndexRoute,
  AuthenticatedAppOrgSlugTablesTableIdSchemaRoute:
    AuthenticatedAppOrgSlugTablesTableIdSchemaRoute,
  AuthenticatedAppOrgSlugTablesTableIdIndexRoute:
    AuthenticatedAppOrgSlugTablesTableIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicSlugTableIdRouteChildren {
  PublicSlugTableIdRecordIdRoute: typeof PublicSlugTableIdRecordIdRoute
  PublicSlugTableIdFormRoute: typeof PublicSlugTableIdFormRoute
  PublicSlugTableIdIndexRoute: typeof PublicSlugTableIdIndexRoute
}

const PublicSlugTableIdRouteChildren: PublicSlugTableIdRouteChildren = {
  PublicSlugTableIdRecordIdRoute: PublicSlugTableIdRecordIdRoute,
  PublicSlugTableIdFormRoute: PublicSlugTableIdFormRoute,
  PublicSlugTableIdIndexRoute: PublicSlugTableIdIndexRoute,
}

const PublicSlugTableIdRouteWithChildren =
  PublicSlugTableIdRoute._addFileChildren(PublicSlugTableIdRouteChildren)

interface ApiPublicSlugTableIdRouteChildren {
  ApiPublicSlugTableIdRecordIdRoute: typeof ApiPublicSlugTableIdRecordIdRoute
  ApiPublicSlugTableIdSubmitRoute: typeof ApiPublicSlugTableIdSubmitRoute
}

const ApiPublicSlugTableIdRouteChildren: ApiPublicSlugTableIdRouteChildren = {
  ApiPublicSlugTableIdRecordIdRoute: ApiPublicSlugTableIdRecordIdRoute,
  ApiPublicSlugTableIdSubmitRoute: ApiPublicSlugTableIdSubmitRoute,
}

const ApiPublicSlugTableIdRouteWithChildren =
  ApiPublicSlugTableIdRoute._addFileChildren(ApiPublicSlugTableIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  LeadTokenRoute: LeadTokenRoute,
  ApiPublicInstanceSettingsRoute: ApiPublicInstanceSettingsRoute,
  ApiPublicOrganizationCategoriesRoute: ApiPublicOrganizationCategoriesRoute,
  ApiPublicOrganizationsRoute: ApiPublicOrganizationsRoute,
  ApiPublicPlatformLabelsRoute: ApiPublicPlatformLabelsRoute,
  ApiPublicRecordsRoute: ApiPublicRecordsRoute,
  ApiPublicSystemFieldsRoute: ApiPublicSystemFieldsRoute,
  ApiPublicTablesRoute: ApiPublicTablesRoute,
  PublicSlugTableIdRoute: PublicSlugTableIdRouteWithChildren,
  PublicSlugIndexRoute: PublicSlugIndexRoute,
  ApiPublicSlugTableIdRoute: ApiPublicSlugTableIdRouteWithChildren,
  ApiPublicCampaignsRecordIdRoute: ApiPublicCampaignsRecordIdRoute,
  ApiPublicCategoryLayoutCategoryIdRoute:
    ApiPublicCategoryLayoutCategoryIdRoute,
  ApiPublicCategorySchemaCategoryIdRoute:
    ApiPublicCategorySchemaCategoryIdRoute,
  ApiPublicFormSchemaViewIdRoute: ApiPublicFormSchemaViewIdRoute,
  ApiPublicLeadTokenRoute: ApiPublicLeadTokenRoute,
  ApiPublicViacepCepRoute: ApiPublicViacepCepRoute,
  PublicSlugCampaignsRecordIdRoute: PublicSlugCampaignsRecordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
