/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppOrgSlugIndexRouteImport } from './routes/_authenticated.app.$orgSlug.index'
import { Route as AuthenticatedAppOrgSlugTablesTableIdIndexRouteImport } from './routes/_authenticated.app.$orgSlug.tables.$tableId.index'
import { Route as AuthenticatedAppOrgSlugTablesTableIdSchemaRouteImport } from './routes/_authenticated.app.$orgSlug.tables.$tableId.schema'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppOrgSlugIndexRoute =
  AuthenticatedAppOrgSlugIndexRouteImport.update({
    id: '/app/$orgSlug/',
    path: '/app/$orgSlug/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppOrgSlugTablesTableIdIndexRoute =
  AuthenticatedAppOrgSlugTablesTableIdIndexRouteImport.update({
    id: '/app/$orgSlug/tables/$tableId/',
    path: '/app/$orgSlug/tables/$tableId/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppOrgSlugTablesTableIdSchemaRoute =
  AuthenticatedAppOrgSlugTablesTableIdSchemaRouteImport.update({
    id: '/app/$orgSlug/tables/$tableId/schema',
    path: '/app/$orgSlug/tables/$tableId/schema',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/$orgSlug/': typeof AuthenticatedAppOrgSlugIndexRoute
  '/app/$orgSlug/tables/$tableId/schema': typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  '/app/$orgSlug/tables/$tableId/': typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/$orgSlug': typeof AuthenticatedAppOrgSlugIndexRoute
  '/app/$orgSlug/tables/$tableId/schema': typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  '/app/$orgSlug/tables/$tableId': typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/$orgSlug/': typeof AuthenticatedAppOrgSlugIndexRoute
  '/_authenticated/app/$orgSlug/tables/$tableId/schema': typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  '/_authenticated/app/$orgSlug/tables/$tableId/': typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/'
    | '/app/$orgSlug/'
    | '/app/$orgSlug/tables/$tableId/schema'
    | '/app/$orgSlug/tables/$tableId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app'
    | '/app/$orgSlug'
    | '/app/$orgSlug/tables/$tableId/schema'
    | '/app/$orgSlug/tables/$tableId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/'
    | '/_authenticated/app/$orgSlug/'
    | '/_authenticated/app/$orgSlug/tables/$tableId/schema'
    | '/_authenticated/app/$orgSlug/tables/$tableId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$orgSlug/': {
      id: '/_authenticated/app/$orgSlug/'
      path: '/app/$orgSlug'
      fullPath: '/app/$orgSlug/'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$orgSlug/tables/$tableId/': {
      id: '/_authenticated/app/$orgSlug/tables/$tableId/'
      path: '/app/$orgSlug/tables/$tableId'
      fullPath: '/app/$orgSlug/tables/$tableId/'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugTablesTableIdIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/$orgSlug/tables/$tableId/schema': {
      id: '/_authenticated/app/$orgSlug/tables/$tableId/schema'
      path: '/app/$orgSlug/tables/$tableId/schema'
      fullPath: '/app/$orgSlug/tables/$tableId/schema'
      preLoaderRoute: typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppOrgSlugIndexRoute: typeof AuthenticatedAppOrgSlugIndexRoute
  AuthenticatedAppOrgSlugTablesTableIdSchemaRoute: typeof AuthenticatedAppOrgSlugTablesTableIdSchemaRoute
  AuthenticatedAppOrgSlugTablesTableIdIndexRoute: typeof AuthenticatedAppOrgSlugTablesTableIdIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppOrgSlugIndexRoute: AuthenticatedAppOrgSlugIndexRoute,
  AuthenticatedAppOrgSlugTablesTableIdSchemaRoute:
    AuthenticatedAppOrgSlugTablesTableIdSchemaRoute,
  AuthenticatedAppOrgSlugTablesTableIdIndexRoute:
    AuthenticatedAppOrgSlugTablesTableIdIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
